### ISSUE TITLE
More Details about which 9 combinations used for training and the 3 combinations used for validation

### ISSUE THREAD

**Issue by L0Ding** [kanz76/ComGNN#1]
Your contribution adds great value. I'd be interested to know which 9 data combinations were used for training, and which 3 data combinations were used for validation, as mentioned in Section 5.1. dataset in your paper. I'm very interested in the specifics of the datasets you worked with. 
Could you please provide more details about the 9 combinations used for training and the 3 combinations used for validation?

**Comment by kanz76** [comment]
Hello, 

I have updated the repo (README file) with details about the training and validation sets. 
I hope you find it useful.
